### ISSUE TITLE
path checking and joining not working on Windows

### ISSUE THREAD

**Issue by reijosirila** [dai-shi/connect-cache-manifest#3]
"if (entry.file.lastIndexOf(path.sep, 0) !== 0) {" not working on Windows if its full path defined.

**Comment by dai-shi** [comment]
Oh, nice catch!
Do you have any suggestion how to check full paths on Windows?
Thanks.

**Comment by reijosirila** [comment]
Maybe
https://nodejs.org/api/path.html#path_path_isabsolute_path ?

**Comment by dai-shi** [comment]
Thanks. I see. It's a new api from v0.12. I wonder if we can drop v0.10 support.

**Comment by reijosirila** [comment]
I don't mind :)

**Comment by dai-shi** [comment]
Hm, I will try to support both.

**Comment by dai-shi** [comment]
Does it work for you?

**Comment by dai-shi** [comment]
Just released v0.2.2 at npmjs.com.

**Comment by reijosirila** [comment]
Thanks. It works great!
